import { inngest } from './client';
import { prisma, tenantStorage } from '@/lib/prisma';
import { EmailService } from '@/lib/email/EmailService';
import { renderTemplate } from '@/lib/templates/render';
import { advanceSequence } from '@/lib/sequences/engine';
import { canSendNow, incrementSendCount } from '@/lib/sequences/smartSend';

/**
 * Serverless job runner for scheduled tasks (automated emails generated by sequences).
 * Triggered at the task's due date by Inngest.
 */
export const executeScheduledTask = inngest.createFunction(
  { 
    id: 'execute-scheduled-task', 
    name: 'Execute Scheduled Task',
    concurrency: {
      limit: 10, // Max 10 concurrent email sends across the serverless environment
    },
    triggers: [{ event: 'crm/task.execute' }]
  },
  async ({ event, step }: { event: any; step: any }) => {
    const { taskId } = event.data;

    // 1. Fetch task details (with RLS bypassed to look up the task's tenant ID)
    const task = await tenantStorage.run({ tenantId: 'system', bypassRls: true }, async () => {
      return await step.run('fetch-task', async () => {
        return await prisma.task.findUnique({
          where: { id: taskId },
          include: {
            lead: {
              include: {
                assignedTo: {
                  select: { id: true, firstName: true, lastName: true, role: true },
                },
              },
            },
          },
        });
      });
    });

    if (!task) return { status: 'ignored', reason: 'task_not_found' };
    if (task.status !== 'pending') return { status: 'ignored', reason: `task_status_is_${task.status}` };

    // Execute the remaining operations inside the task's tenant context
    return await tenantStorage.run({ tenantId: task.tenantId }, async () => {
      // We only automate autoComplete email tasks generated by sequences
      const isAutoEmail = task.type === 'email' && task.sequenceId !== null;
      if (!isAutoEmail) {
        return { status: 'manual_action_required', type: task.type };
      }

      // 2. Verify enrollment eligibility
      const enrollmentEligible = await step.run('check-eligibility', async () => {
        const stepInfo = await prisma.sequenceStep.findFirst({
          where: { sequenceId: task.sequenceId!, order: task.sequenceStep ?? -1 },
          include: { template: { include: { abVariants: true } } },
        });

        const eligible =
          stepInfo?.autoComplete &&
          stepInfo.channel === 'email' &&
          stepInfo.template &&
          task.lead.sequenceId === task.sequenceId &&
          task.lead.sequenceStatus === 'active' &&
          !task.lead.emailInvalid &&
          task.lead.email;

        return { eligible: !!eligible, template: stepInfo?.template, order: stepInfo?.order };
      });

      if (!enrollmentEligible.eligible || !enrollmentEligible.template) {
        return { status: 'skipped', reason: 'lead_ineligible_or_paused' };
      }

      const { template, order } = enrollmentEligible;

      // 3. Fetch sending mailbox account
      const account = await step.run('fetch-mailbox', async () => {
        return await prisma.emailAccount.findFirst({
          where: { userId: task.lead.assignedToId, isActive: true },
        });
      });

      if (!account) {
        return { status: 'failed', reason: 'no_active_mailbox_connected' };
      }

      // 4. Verify sending limits
      const sendAllowed = await step.run('check-rate-limit', async () => {
        return await canSendNow(account.id);
      });

      if (!sendAllowed) {
        // Re-schedule this task to check again in 15 minutes
        const rescheduleTime = new Date(Date.now() + 15 * 60 * 1000);
        await step.run('reschedule-task', async () => {
          await prisma.task.update({
            where: { id: task.id },
            data: { dueDate: rescheduleTime },
          });
        });
        
        await inngest.send({
          name: 'crm/task.execute',
          data: { taskId: task.id },
          ts: rescheduleTime.getTime(),
        });
        
        return { status: 'rescheduled', reason: 'daily_send_limit_reached' };
      }

      // 5. Concurrency lock
      const locked = await step.run('lock-task', async () => {
        const result = await prisma.task.updateMany({
          where: { id: task.id, status: 'pending' },
          data: { lockedAt: new Date() },
        });
        return result.count === 1;
      });

      if (!locked) {
        return { status: 'ignored', reason: 'concurrency_lock_failed' };
      }

      // 6. Render template (handling A/B testing variants)
      const renderPayload = await step.run('render-email-body', async () => {
        let subject: string;
        let body: string;
        let selectedVariantId: string | null = null;

        const variantA = template.abVariants?.find((v: any) => v.version === 'A');
        const variantB = template.abVariants?.find((v: any) => v.version === 'B');
        if (variantA && variantB) {
          const useB = Math.random() < 0.5;
          const selected = useB ? variantB : variantA;
          subject = renderTemplate(selected.subject ?? template.subject ?? '', task.lead, task.lead.assignedTo);
          body = renderTemplate(selected.body ?? template.body, task.lead, task.lead.assignedTo);
          selectedVariantId = selected.id;
        } else {
          subject = renderTemplate(template.subject ?? '', task.lead, task.lead.assignedTo);
          body = renderTemplate(template.body, task.lead, task.lead.assignedTo);
        }

        return { subject, body, selectedVariantId };
      });

      // 7. Fire email send API
      await step.run('send-email', async () => {
        const emailService = await EmailService.fromAccount(account);
        await emailService.send({
          from: account.email,
          to: task.lead.email,
          subject: renderPayload.subject,
          text: renderPayload.body,
          html: renderPayload.body.replace(/\n/g, '<br>'),
        });
      });

      // 8. Update DB statuses and advance sequence
      await step.run('complete-operations', async () => {
        await incrementSendCount(account.id);

        await prisma.task.update({
          where: { id: task.id },
          data: { status: 'completed', completedAt: new Date() },
        });

        if (renderPayload.selectedVariantId) {
          await prisma.abTestVariant.update({
            where: { id: renderPayload.selectedVariantId },
            data: { sentCount: { increment: 1 } },
          });
        }

        await prisma.lead.update({
          where: { id: task.leadId },
          data: {
            lastContactedAt: new Date(),
            emailSentCount: { increment: 1 },
          },
        });

        await prisma.activity.create({
          data: {
            userId: task.lead.assignedToId,
            leadId: task.leadId,
            type: 'email_sent',
            channel: 'email',
            description: `Auto-sent sequence step ${order} via serverless Inngest queue`,
            metadata: {
              auto: true,
              accountId: account.id,
              subject: renderPayload.subject,
              taskId: task.id,
              sequenceId: task.sequenceId,
              sequenceStep: order,
            },
          },
        });

        await advanceSequence(task, task.lead.assignedToId);
      });

      return { status: 'completed', taskId: task.id };
    });
  }
);

